const exportObject = Object.freeze({
  INITIALIZE_GAME_PLAY: 'initializeGameplay',
  REJOIN_TIMER_EXPIRED: 'rejoinTimerExpired',
  REJOIN_TIMER_CANCELLED: 'rejoinTimerCancelled',
  PLAYER_TURN_TIMER_EXPIRED: 'playerTurnTimerExpired',
  PLAYER_TURN_TIMER_CANCELLED: 'playerTurnTimerCancelled',
  TABLE_SNAPSHOT_CANCELLED: 'tableSnapshotCancelled',
  INITIAL_GAME_TIMER: 'initialGameTimer',
  PLAY_MORE_POPUP_EXPIRED: 'playMorePopUpExpired',
  PLAY_MORE_POPUP_CANCELLED: 'playMorePopUpCancelled',
  ROUND_ANIMATION_EXPIRED: 'roundAnimationExpired',
  SCORE_BOARD_TIMER_EXPIRED: 'scoreBoardTimerExpired',
  DEALS_ANIMATION_END: 'dealsAnimationEnd',
  DEALS_AFTER_START_END: 'dealsAfterStartEnd',
  FINISH_TIMER_EXPIRED: 'finishTimerExpired',
  FINISH_TIMER_CANCELLED: 'finishTimerCancelled',
  SEND_DONE_EVENT_TO_PLAYER: 'DONE_EVENT',
  ROUND_STARTED: 'ROUND_STARTED',
  INITIAL_TURN_SETUP_TIMER_EXPIRED: 'initialTurnSetupTimerExpired',
  INITIAL_BID_TURN_SETUP_TIMER_EXPIRED: 'initialBidTurnSetupTimerExpired',
  PLAYER_BID_TURN_TIMER_EXPIRED: 'playerBidTurnTimerExpired',
  PLAYER_BID_TURN_TIMER_CANCELLED: 'playerBidTurnTimerCancelled',
  WIN_OF_ROUND_TIMER: 'WIN_OF_ROUND_TIMER',
  WINNER_DECLARE_TIMER: 'WINNER_DECLARE_TIMER',
  START_NEW_ROUND_TIMER: 'START_NEW_ROUND_TIMER',
  TIME_OUT_TO_LEAVE_TABLE: 'TIME_OUT_TO_LEAVE_TABLE',
  ROUND_START_TIMER_CANCELLED: 'roundStartTimerCancel',
  NEW_ROUND_START_TIMER_CANCELLED: 'roundStartTimerCancel',
  BOT_BID_TURN_TIMER_FOR_FTUE: 'botBidTurnTimerForFtue',
  FIND_BOT: 'findBot',
  TACK_BOT_BID_TURN: 'TACK_BOT_BID_TURN',
  TACK_BOT_TURN: 'TACK_BOT_TURN',
});
export = exportObject;
