import EVENT_EMITTER from "./eventEmitter";
import SOCKET from "./socket";
import MESSAGES from "./messages";
import MONGO from "./mongo";
import REDIS from "./redis";
import NUMERICAL from "./numerical";
import PLAYER_STATE from "./playerState";
import TABLE_STATE from "./tableState";
import SINGLE_DECK from "./singleDeck";
import CARD_SEQUENCE from "./cardSequence";
import ERROR_TYPE from "./error";
import STATIC_USER_CARD from "./staticUserCard";
import FTUE_STEP from "./ftueStep";
import HELP_RULES from './helpRules'
import BULL from './bull';
import BOT from "./bot";

const exportObject = Object.freeze({
  PRODUCTION: "production",
  POPUP_TITLE: { ALERT: "Alert" },
  FTUE_BOT: "FTUE_BOT",
  ACKNOWLEDGE_EVENT: "Acknowledge Event",
  EVENTS: {
    WINNING_AMOUNT_BREAKDOWN: 'WINNING_AMOUNT_BREAKDOWN',
    ERROR_SOCKET_EVENT: "ERROR",
    DONE_SOCKET_EVENT: "DONE",
    HEART_BEAT_SOCKET_EVENT: "HEART_BEAT",
    SIGN_UP_SOCKET_EVENT: "SIGNUP",
    GAME_TABLE_INFO_SOCKET_EVENT: "GAME_TABLE_INFO",
    JOIN_TABLE_SOCKET_EVENT: "JOIN_TABLE",
    ROUND_TIMER_STARTED_SOCKET_EVENT: "ROUND_TIMER_STARTED",
    COLLECT_BOOT_VALUE_SOCKET_EVENT: "COLLECT_BOOT_VALUE",
    USER_BID_SOCKET_EVENT: "USER_BID",
    USER_THROW_CARD_SOCKET_EVENT: "USER_THROW_CARD",
    LEAVE_TABLE_SCOKET_EVENT: "LEAVE_TABLE",
    TIME_OUT_LEAVE_TABLE_POPUP_SCOKET_EVENT: "TIME_OUT_LEAVE_TABLE_POPUP",
    LOCK_IN_PERIOD_POPUP_SCOKET_EVENT: "LOCK_IN_PERIOD",
    ADD_PLAYER_IN_TABLE_ROOM: "APITR",
    SHOW_MY_CARDS_SOCKET_EVENT: "SHOW_MY_CARDS",
    USER_TURN_STARTED_SOCKET_EVENT: "USER_TURN_STARTED",
    USER_BID_TURN_STARTED_SOCKET_EVENT: "USER_BID_TURN_STARTED",
    USER_BID_SHOW_SOCKET_EVENT: "USER_BID_SHOW",
    USER_THROW_CARD_SHOW_SOCKET_EVENT: "USER_THROW_CARD_SHOW",
    WIN_OF_ROUND_SOCKET_EVENT: "WIN_OF_ROUND",
    SCORE_OF_ROUND_SOCKET_EVENT: "SCORE_OF_ROUND",
    WINNER_DECLARE_SOCKET_EVENT: "WINNER_DECLARE",
    SHOW_SCORE_BOARD: "SHOW_SCORE_BOARD",
    NEW_GAME_START: "NEW_GAME_START",
    DISCONNECT: "disconnect",
    REJOIN_SOCKET_EVENT: "REJOIN",
    BACK_IN_GAME_PLAYING_SOCKET_EVENT: "BACK_IN_GAME_PLAYING",
    INSUFFICIENT_FUND_SOCKET_EVENT: "testingEvent",
    SHOW_POPUP_ERROR_MESSAGES_SOCKET_EVENT: "OPEN_GAME_POPUP",
    SHOW_POPUP: "SHOW_POPUP",
    SHOW_POPUP_WITH_METHOD: "SHOW_POPUP_WITH_METHOD",
    FTUE_MESSAGE_SOCKET_EVENT: "FTUE_MESSAGE",
    FTUE_CHANGE_STEP_SOCKET_EVENT: "FTUE_CHANGE_STEP",
    SIGNUP_FOR_BOT: "signUpForBot",
    GTI_INFO_SOCKET_EVENT: "GTI_INFO",
    GAME_SETTING_MENU_HELP_SOCKET_EVENT: "HELP",
    RESUFFLE_CARDS: "RESUFFLE_CARDS",
    REJOIN_POPUP_SOCKET_EVENT: "REJOIN_POPUP",
    REJOIN_OR_NEW_GAME_SOCKET_EVENT: "REJOIN_OR_NEW_GAME"
  },
  INSTRUMENTATION_EVENTS: {
    USER_STOOD_UP: "User Stood Up",
    USER_PLAYED_GAME: "User Played Game",
    USER_PLAYED_SPADES: "User Played Spades",
    USER_GAME_REJOINED: "User Game Rejoined",
    USER_TABLE_EXITED: "User Table Exited",
    USER_TABLE_JOINED: "User Table Joined",
    USER_SPADES_ROUND_STARTED: "User Spades Round Started",
    USER_SPADES_SESSION_STATUS: "User Spades Session Status",
  },
  GAME_TYPE: {
    SOLO: "SPDS",
    FTUE_SOLO: "FTUE_SPDS",
  },
  GAME_PREFIX: {
    SOLO: "SPDS",
  },
  HISTORY: {
    CARD_THROW_TURN: "cardThrow",
    TIME_OUT: "timeOut",
  },
  EVENT_EMITTER,
  SOCKET,
  MESSAGES,
  MONGO,
  REDIS,
  NUMERICAL,
  PLAYER_STATE,
  TABLE_STATE,
  SINGLE_DECK,
  CARD_SEQUENCE,
  ERROR_TYPE,
  FROM_CANCEL_BATTLE: "FROM_CANCEL_BATTLE",
  COUNTRY: "IN",
  SNS_KEYS: {
    FINISH_TABLE_KEY: "card-game-spades-finish-table-event-consumer",
    CANCEL_BATTLE_KEY: "card-game-cancel-battle-event-consumer",
  },
  STATIC_USER_CARD,
  FTUE_STEP,
  HELP_RULES,
  EMPTY: '',
  BULL,
  BOT,
});
export = exportObject;
